version: '3.8'
services:
  rag-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8001
    ports:
      - "5173:80"
    env_file:
      - .env.docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
